### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by andrewharvey** [peterqliu/threebox#21]
@kronick 05f9934f46e1360e689c72aa24f4bbde1ea4b7bc seems to have broken the build. I needed to do https://github.com/andrewharvey/threebox/commit/bd610cfb3e04f71a6123120fc8b24ecda1ae7b45 to get it working.

**Comment by kronick** [comment]
Sorry about that; I forgot to include `exports.js` in that commit. Should be there now with https://github.com/peterqliu/threebox/commit/34c3cb982cbf8db8b006f52d90eb3dc5cdec35ae .
