### ISSUE TITLE
Question: is threebox + three.js terrain mesh possible?

### ISSUE THREAD

**Issue by clintharris** [peterqliu/threebox#29]
Is there any reason why it wouldn't be possible to use threebox as you've documented, but _also_ add a `THREE.PlaneGeometry` terrain mesh to the MapBox GL map (as described by Peter [here](https://blog.mapbox.com/bringing-3d-terrain-to-the-browser-with-three-js-410068138357))?

**Comment by peterqliu** [comment]
It's certainly possible, but since the terrain mesh covers the whole map, the mapboxgl context on which `threebox` sits atop is unnecessary.
