### ISSUE TITLE
Setting castShadow causes blank render

### ISSUE THREAD

**Issue by AllenWilliamson** [peterqliu/threebox#42]
I'm trying to get shadows working using the latest threebox (with mapbox custom layers). When setting `castShadow` on a `DirectionalLight`, threebox does not render anything. 

Is this a limitation of threebox or has anyone had any luck getting them to work?

**Comment by peterqliu** [comment]
@AllenWilliamson thanks for the note. can you make a test case?

**Comment by AllenWilliamson** [comment]
http://jsfiddle.net/allenw/cwtea0v5/40/

I'm not able to recreate the blank render from my project, but shadows don't seem to be working well either way in the fiddle.

In my project where where the blank render occurs, I can see the first frame render with shadows but then quickly disappears to just show the map. 

It would be great to get some official examples of using shadows in threebox.

**Comment by peterqliu** [comment]
after a bunch of debugging, realized that you needed to add sunlight via `threebox.addAtCoordinate`, rather than `threebox.world.add`. I'm using THREE.SpotLight here, but `DirectionalLight` should work with a bit more finessing.

Please do cut a ticket if you keep seeing the blank render and are able to reproduce -- it likely is related to the map not repainting after the three.js scene updating.

**Comment by danvk** [comment]
@peterqliu Do you have a working demo of a shadow using threebox? The fiddle linked to above produces this for me:

![image](https://user-images.githubusercontent.com/98301/67052352-df9c2f80-f10b-11e9-8513-b5fde4535cec.png)

(Context: [this question](https://stackoverflow.com/questions/58243572/unable-to-cast-a-shadow-with-three-js-and-mapbox-gl))

**Comment by robhawkes** [comment]
I'm also seeing the same results at @danvk when loading the fiddle. I'm currently trying to get shadows working but so far haven't had much luck.

**Comment by jscastro76** [comment]
@robhawkes  @danvk Just FYI, I think I have resolved this quite old request in my [Threebox fork](https://github.com/jscastro76/threebox/issues/30) creating a realistic sun light mode for a given date, time and lnglat combination. I'm about to update the fork with these samples...
**Static**
![MapboxShadow (1)](https://user-images.githubusercontent.com/38470852/89162138-e5b4ad00-d573-11ea-8613-abd291e01446.gif)
**Dynamic**
![EiffelShadow](https://user-images.githubusercontent.com/38470852/89162039-c3bb2a80-d573-11ea-97ca-5af15a9e6720.gif)
