### ISSUE TITLE
Orientation Change breaks map

### ISSUE THREAD

**Issue by regularExpresso** [peterqliu/threebox#43]
changing the device orientation breaks the scale relationship between the mapbox layer and the three.js overlay - any idea how to fix this?

**Comment by regularEspresso** [comment]
hello, has there been any update on this issue by chance?
this is quite a game breaker for my project :/

**Comment by peterqliu** [comment]
Hi! I'm fixing this in the next release, but in the meantime you can do this https://stackoverflow.com/questions/20290402/three-js-resizing-canvas to address changes in viewport size

**Comment by Karma-Studio** [comment]
Thank you, this temporarily fixed it :)

**Comment by peterqliu** [comment]
solved in 0.3.0
