### ISSUE TITLE
how to compare height between 3d modle with mapbox building

### ISSUE THREAD

**Issue by beikehanbao23** [peterqliu/threebox#45]
I have make a 3d model file by 3d max ,output .obj and .mtl  format. The 3d model has  its height and width.

The mapbox basemap  has its 3d building  layer,and also with  height and width.

And how can I see the effect between the obj model and mapbox building .

I wanna it like this 
![image](https://user-images.githubusercontent.com/6064055/50545334-ec1dcd00-0c4a-11e9-9f5e-0659cea43876.png)

![image](https://user-images.githubusercontent.com/6064055/50545356-13c16500-0c4c-11e9-8ada-f1a51e622fd2.png)

but  now It is look like this

![image](https://user-images.githubusercontent.com/6064055/50545330-bd075b80-0c4a-11e9-90ac-9180ab025f3b.png)

Can it  “penetrate”  when the building is heigher than the  3d model(obj)?
@peterqliu   Thanks

**Comment by beikehanbao23** [comment]
My code 


` // Initialize threebox and add obj model
    window.threebox = new Threebox(map);
    threebox.setupDefaultLights();


    function AddAirportModel(modelName, id, sourceUrl, scale) {
            threebox.addSymbolLayer({
                    id:             id,
                    source:         sourceUrl,
                    modelName:      modelName,    // will look for an .obj and .mtl file with this name
                    modelDirectory: "../models/",          // in this directory
                    rotation:       { generator: feature => (new THREE.Euler(Math.PI / 2, 1.4908, feature.properties['heading'] * Math.PI / 180 + Math.PI / 2, "ZXY")) },
                scaleToLatitude: true,
                scale: scale,
                scaleWithMapProjection: true,
                key:{ property: "id" }
        });
        `

`
//add 3d building layer
map.addLayer({
        'id': 'buildings',
        'source': 'airport_buildings',
        'source-layer': 'buildings_merge6_3857',
        // 'filter': ['==', 'extrude', 'true'],
        'type': 'fill-extrusion',
        'minzoom': 14,
        'paint': {
            'fill-extrusion-color': '#B0C4DE',

            // use an 'interpolate' expression to add a smooth transition effect to the
            // buildings as the user zooms in
            'fill-extrusion-height': [
                "interpolate", ["linear"], ["zoom"],
                13, 0,
                13.05, ["get", "gaodu"]
            ],
            'fill-extrusion-base': [
                "interpolate", ["linear"], ["zoom"],
                13, 0,
                13.05, 0
            ],
            'fill-extrusion-opacity': 0.6
        }
    }, "weitu-place-town");
`

**Comment by beikehanbao23** [comment]
![image](https://user-images.githubusercontent.com/6064055/50545369-d27d8500-0c4c-11e9-8e74-71fb344a478a.png)

**Comment by peterqliu** [comment]
adding `renderingMode: '3d'` to the custom layer should be helpful here
