### ISSUE TITLE
don't work with mapbox v51+ 

### ISSUE THREAD

**Issue by GD-Aichi** [peterqliu/threebox#46]
I test mapbox version 51 and 52, but it don't work. All demos don't show anything.
I add "renderingMode: '3d'" in the custom layer, but the same, the objects aren't on the position.

**Comment by mamumu123** [comment]
I found out it, too

**Comment by McCulloughRT** [comment]
proposed fix in #47

**Comment by mamumu123** [comment]
thanks!
