### ISSUE TITLE
mapbox v52+ can not use threebox

### ISSUE THREAD

**Issue by cc-ch** [peterqliu/threebox#49]
mapbox v.0.50.0. 
the map parameter has  **this.map.transform.x**
![image](https://user-images.githubusercontent.com/19361098/53676049-50571e80-3cd8-11e9-8ca8-d6326b35269d.png)

![image](https://user-images.githubusercontent.com/19361098/53676130-4681eb00-3cd9-11e9-8938-1cdfb88b3d57.png)

mapbox v0.52.0 and later don't has the parameter, In threebox,the camera use the parmaters for the camera. 

what the parameter means? I used to translate the  **this.map._center** to Mercator coordinate instead of the parmater,but not work.

**Comment by McCulloughRT** [comment]
Proposed fix is in #47

**Comment by cc-ch** [comment]
thx

**Comment by cc-ch** [comment]
thx

**Comment by peterqliu** [comment]
merged PR 👆

**Comment by zhixing121** [comment]
> thx
can you use it on 0.53 ? I fixed the threebox.js with #47 ,but it didn't work with 0.53.
