### ISSUE TITLE
mapbox build layer will  cover the threebox 3D modle

### ISSUE THREAD

**Issue by cc-ch** [peterqliu/threebox#50]
Display the 3D building by mapbox . And use the mapbox custom layer to add  thrrebox models. the tier has some problem.

![image](https://user-images.githubusercontent.com/19361098/53714723-6ad0f980-3e8a-11e9-802b-3cd97d83f315.png)

![image](https://user-images.githubusercontent.com/19361098/53714735-758b8e80-3e8a-11e9-93b6-009c255c169d.png)

change the config. The effect like this:

![image](https://user-images.githubusercontent.com/19361098/53714779-a966b400-3e8a-11e9-8b95-9728f6cfc7d1.png)

![image](https://user-images.githubusercontent.com/19361098/53714786-acfa3b00-3e8a-11e9-8a8d-801360e0e045.png)

How to combine the mapbox 3D building with threebox 3D models.

**Comment by peterqliu** [comment]
@cc-ch thanks for the issue. can you make a test case? it might help if you add 
`renderingMode: '3d'` to the custom layer

**Comment by AmeliaWang93** [comment]
Thanks a lot! Adding `renderingMode: '3d'` also help me solve the problem. When I add a obj file which contains many buildings, those buildings, which should be occluded, show in front of others.
