### ISSUE TITLE
Unable to add GLTF models to mapbox gl in v0.51.0 onwards

### ISSUE THREAD

**Issue by jackmbox** [peterqliu/threebox#53]
var loader = new THREE.GLTFLoader();            
            loader.load(model3DSrc, (function (gltf) {

                gltf.scene.rotation.x = modelRotate[0];
                
                threebox.addAtCoordinate(gltf.scene, modelOrigin);
}

the above works for and the model can be seen added to the mapbox map canvas:
 <script src='https://api.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.js'></script>
 <link href='https://api.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.css' rel='stylesheet' />

but after updating the mapbox version to v0.51.0 onwards to v0.53.0, the model is added but it cannot be seen on the map anymore.

**Comment by peterqliu** [comment]
@jackmbox can you make a test case?

**Comment by AmeliaWang93** [comment]
I tried to load models with different versions of mapbox, and I find that the file in `dist/threebox.js` is the version only for mapbox v50. It's necessary to build the file with source code by yourself if you use mapbox v50+. I think it will be the best if the author can update the files for more users.

**Comment by jackmbox** [comment]
> I tried to load models with different versions of mapbox, and I find that the file in `dist/threebox.js` is the version only for mapbox v0.50. It's necessary to build the file with source code by yourself if you use mapbox v0.50+. I think it will be the best if the author can update the files for more users.

I've tried rebuilding the file with the source code and it works with v0.53.1 now. Thanks for the awesome work.

**Comment by bennlich** [comment]
@jackmbox @peterqliu maybe would be good to commit the new build to master/dist? I just ran into this problem too.
