### ISSUE TITLE
rotation animation question/bug

### ISSUE THREAD

**Issue by bennlich** [peterqliu/threebox#55]
Hey there! I'm rendering a (TubeBufferGeometry, ShaderMaterial) object with threebox. The ShaderMaterial animates some flowing colors over time. When I leave the rotation of the object alone, everything looks dandy:

![static-tube](https://user-images.githubusercontent.com/704368/56084954-1e190080-5df0-11e9-9b38-2777f8a1d758.gif)

When I add:

```
mesh.rotation.z += 0.02;
mesh.rotation.y += 0.07;
```
to my animation loop, I start to see some weirdness:

![rotating-tube](https://user-images.githubusercontent.com/704368/56084961-4274dd00-5df0-11e9-8e5d-c62a97fac3f4.gif)

It looks to me like several tubes are getting rendered, slightly displaced in time. Any idea what's going on?

If in my animation loop I use:
```
threebox.update(true);
```
the tube looks fine, but the map disappears.

![tube-no-map](https://user-images.githubusercontent.com/704368/56084987-c62ec980-5df0-11e9-9f5f-3d65b6454100.gif)

**Comment by peterqliu** [comment]
Hi @bennlich , that looks interesting. Can you make a test case to help debugging?

**Comment by bennlich** [comment]
Sure thing @peterqliu. What would be helpful? Some minimal amount of code that reproduces the glitch?

**Comment by peterqliu** [comment]
Yes, a jsfiddle or some equivalent

**Comment by bennlich** [comment]
I had trouble getting threebox.js to load in a fiddle (seemed like `Threebox` wasn't attaching to the window object in their loader?), so here's a gist: https://gist.github.com/bennlich/ac7962b8fda70ae65f8a4d031384eaa1.

Interestingly, it doesn't seem to happen if I rotate only about the z-axis.

**Comment by peterqliu** [comment]
@bennlich thanks for the gist! `threebox.update()` calls a rerender of the threebox scene, which draws over the rest of the map (as you saw when you set it to `true` and it went blank). To avoid this, the `false` option subsequently [forces mapbox GL to redraw the rest of the map](https://github.com/peterqliu/threebox/blob/master/src/Threebox.js#L81). This redraw operation _might_ somehow be redrawing the tube animation as well at a slightly offset time, which could explain what we're seeing.

Any fix here likely lies upstream in gl-js -- [this PR](https://github.com/mapbox/mapbox-gl-js/pull/8131) might be promising in giving us more control over rendering

**Comment by peterqliu** [comment]
@bennlich after chatting with some other developers, we can actually solve this by letting mapbox gl schedule all the animations. 

Instead of calling `threebox.update` within your `animate` loop, call a repaint via `map.triggerRepaint()`, and it'll do an update inside that internal rendering schedule

**Comment by bennlich** [comment]
Excellent! Thank you for your help! Makes sense. I forgot that we are already calling threebox.update() within the render callback.
