### ISSUE TITLE
Transparency example

### ISSUE THREAD

**Issue by bennlich** [peterqliu/threebox#58]
I'd love an example with a transparent object :)

**Comment by bennlich** [comment]
Here's a gist based on the basic cube example where I try to make the red cube transparent (to no avail):

https://gist.github.com/bennlich/6c8282c9429f3342eb645a4575b6b536

![Screenshot from 2019-05-10 10-21-06](https://user-images.githubusercontent.com/704368/57544850-6f43e380-730d-11e9-850a-82774ecd7c0a.png)

**Comment by bennlich** [comment]
I think I just don't understand how to use `alphaMap`s properly. Using the `transparent` and `opacity` properties seems to work as expected. E.g.:
```
var redMaterial = new THREE.MeshPhongMaterial({
    color: 0x660000,
    transparent: true,
    opacity: 0.5
});
```
![Screenshot from 2019-05-10 13-45-38](https://user-images.githubusercontent.com/704368/57555757-fa32d700-7329-11e9-8960-2f6d393ea8b9.png)

**Comment by peterqliu** [comment]
@bennlich yes, THREE requires `transparent: true` whenever you want to render things that aren't fully opaque. this enables it to skip depth testing behind opaque things.
