### ISSUE TITLE
Extrusion Buffer Geometry rendering transparent/inside-out.

### ISSUE THREAD

**Issue by akexinad** [peterqliu/threebox#70]
In the screenshot is an example of 'compartment' extrusions rendering on top of one another, like the floors to a building.

When I pass THREE.Shape to create a THREE.ExtrusionBufferGeometry, the extrusions above the initial extrusion at the very bottom seem to render without side faces/transparently. You can see the top/bottom face of each in extrusion in black.

I use the tb.Object3D method as per the example in the Threebox repo. Am I supposed to be rendering extrusions differently? 

![Screen Shot 2019-07-26 at 07 05 41](https://user-images.githubusercontent.com/44803303/61908917-24cd1d00-af74-11e9-8a5f-352f3b7f9825.png)

**Comment by ulrikborjesson** [comment]
this might be related to my issue #69

**Comment by akexinad** [comment]
> this might be related to my issue #69

Hey @ulrikborjesson thanks for the comment.

I found that setting my material transparency to true and opacity to one solved the issue:

`const material = new THREE.MeshLambertMaterial({
    color: '#D40000',
    transparency: true,
    opacity: 1
});`

This is using npm threebox on angular 8.

I doubt this is a real solution, because the are still some extrusions that show some level of transparency.

I might have to try out your method of updating the threejs library in the future.

![Capture](https://user-images.githubusercontent.com/44803303/62251567-7d4c6080-b433-11e9-937a-82e79df10191.PNG)
