### ISSUE TITLE
model disappear  when pitch changed

### ISSUE THREAD

**Issue by likeswinds** [peterqliu/threebox#74]
like this 

![model](https://user-images.githubusercontent.com/7099174/63645125-12d4ca80-c72a-11e9-8a9c-d87e0522bd8b.gif)

hope to fixed

CameraSync constructor
```
    this.map
        .on('move', function() {
            _this.updateCamera()
        })
       // add this code
        .on('pitch', function() {
            _this.setupCamera();
        })
        .on('resize', function(){
            _this.setupCamera();
        })
```

**Comment by jscastro76** [comment]
Hi @likeswinds, this bug has been resolved in this [fork](https://github.com/jscastro76/threebox) changing the calculation of the nearest/furthest values.
